export const APP_NAME = "Innershift" 

// Color Scheme
export const LIGHT_GREEN = "#CCE8E5"
export const BRIGHT_GREEN = "#8AC8C2"
export const OLIVE = "#6FB7AF"
export const DARK_OLIVE = "#5EA49B"
export const LIGHT_GREEN2 = "#FFFFFF"
export const HIGHLIGHT_GREEN = "#4CC59A"
export const DARK_GREEN = "#477E77"
export const BG = "#EFFFFF"
export const GREY = "#F3F3F3"
export const DARK_GREY = "#757575"
export const DESKTOP_BG_LIGHT="#EDF7F6"
export const DESKTOP_BG_MEDIUM = "#DCEFED"